### ISSUE TITLE
Improve SpringData custom repository implementation support.

### ISSUE THREAD

**Issue by christophstrobl** [spring-projects-experimental/spring-graalvm-native#158]
Lookup and register custom implementations of SpringData repository fragments.

```java
interface OrderRepository extends CrudRepository<Order, String>, OrderRepositoryCustom {
  // ..
}

@Component
class OrderRepositoryImpl implements OrderRepositoryCustom {
  // ..
}
```

Investigate how far it is possible to move away from the default `Impl` postfix towards reading the `repositoryImplementationPostfix` value if set.

Check if it is required to have the `@Component` annotation on the actual custom implementation or if there's a way around it.

**Comment by sdeleuze** [comment]
Rollbacked due to error on Java 11 builds (on [20.1](https://ci.spring.io/teams/spring-graalvm-native/pipelines/spring-graalvm-native/jobs/20.1-dev-java11-samples-build/builds/79) and [master](https://ci.spring.io/teams/spring-graalvm-native/pipelines/spring-graalvm-native/jobs/master-java11-samples-build/builds/34)).
