### ISSUE TITLE
Autodetect 'start-class' from SpringBootApplication annotation

### ISSUE THREAD

**Issue by jkroepke** [spring-projects-experimental/spring-graalvm-native#179]
Hi,

please correct me if I wrong, but on the most Spring Boot projects. The start-class does have the `@SpringBootApplication` annotation.

The maven plugin could use the class annotated by `@SpringBootApplication` as as `start-class` property for native-image. 

One more less manual configuration for users.

**Comment by sdeleuze** [comment]
@eginez I guess the issue here is the lack of integration between Spring Boot and GraalVM native image plugins. Do you think there could be extension points in GraalVM feature that could allows `spring-graalvm-native` to specify the start class to use?

**Comment by jkroepke** [comment]
Looking at https://github.com/oracle/graal/blob/master/substratevm/src/native-image-maven-plugin/src/main/java/com/oracle/substratevm/NativeImageMojo.java#L364-L386 I could not find any extension point. I opened an issue on the graal project.

**Comment by jkroepke** [comment]
Could the `native-image.properties` an extension point by append the `-H:Class` option?

**Comment by sdeleuze** [comment]
[GraalVM native Maven plugin documentation](https://www.graalvm.org/docs/reference-manual/native-image/#integration-with-maven) specifies:
> you can use -jar and provide a .jar file that specifies the main method in its manifest.

@aclement We could maybe rewrite the manifest during the build process? It probably won't work via GraalVM native feature resource transformation, but we could maybe try via bash for now and do that in dedicated tooling later?

Side note: I am not sure why we use a `start-class` property instead of `mainClass` configuration element of the `native-image-maven-plugin`. Any reason for that?

**Comment by sdeleuze** [comment]
Related pointers provided by @eginez:
 - https://github.com/oracle/graal/blob/master/substratevm/src/native-image-maven-plugin/src/main/java/com/oracle/substratevm/NativeImageMojo.java#L358
 - https://github.com/oracle/graal/blob/master/substratevm/src/native-image-maven-plugin/src/main/java/com/oracle/substratevm/NativeImageMojo.java#L170

**Comment by sdeleuze** [comment]
Superseded by #165.
