### ISSUE TITLE
Check why adding devtools dependency produces an error

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-graalvm-native#214]

**Comment by aclement** [comment]
This is actually due to an `ApplicationListener` entry in the dev tools `spring.factories`:
```
org.springframework.context.ApplicationListener=\
org.springframework.boot.devtools.restart.RestartApplicationListener,\
org.springframework.boot.devtools.logger.DevToolsLogFactory.Listener
```
The `DevToolsLogFactory.Listener` is not resolving because it is an inner. Must be the first time this has been encountered (surprising). Fixed. This kind of issue may surface in other places where inner types are not handled quite right.
