### ISSUE TITLE
Question: Why the project is limited by SpringBoot and doesn't support SpringFramework

### ISSUE THREAD

**Issue by gimlet2** [spring-projects-experimental/spring-graalvm-native#283]
Spring Framework project references this repo https://github.com/spring-projects/spring-framework/wiki/GraalVM-native-image-support as smth that support it for GraalVm native-images. But it looks like **spring-graalvm-native** requires projects to use SpringBoot 2.4.
Is there any plans around this question?

**Comment by aclement** [comment]
This experimental project is a proving ground for flushing out issues that prevent both boot *and* framework from being compatible with native-image. As issues are found code changes are made in both Spring Boot and Spring Framework. We do have a focus on Spring Boot but the changes we've made along the way should mean that spring framework apps will work too. *But* for now you may need to collect the required configuration via the agent rather than employing this feature. Using the agent is covered in here: https://github.com/spring-projects-experimental/spring-graalvm-native/blob/master/spring-graalvm-native-docs/src/main/asciidoc/agent.adoc but the build integration steps would likely be a little different if in a non-boot world. If you are finding framework issues with that approach, we would take a look at them.

**Comment by sdeleuze** [comment]
To complete @aclement answer, I think that indeed our support is for now too much Spring Boot oriented if we have a look to hints triggers, and that moving toward a support that targets more specifically Spring Framework, Data, Security, etc. is probably a software design that would bring some added value in term of maintainability and quality.

I have created the related #342 issue.
