### ISSUE TITLE
Make LogLevel reflection config available conditionally in functional mode

### ISSUE THREAD

**Issue by dsyer** [spring-projects-experimental/spring-graalvm-native#290]
It's a mystery (to me) why it isn't needed in reflection mode, but we need `LogLevel` to be reflectable so that users can set `logging.level.*` configuration and have it behave compatibly. I added a `LogLevelHints` but there's no way currently to make it only work in functional mode.

**Comment by aclement** [comment]
You can set the trigger to be a type only around in functional mode, then the hint will only fire if that type is around e.g. maybe InfrastructureInitializer in a spring-init case - it just gets complicated if it is InfrastructureInitializer *or* KofuApplication *or* JafuApplication (then we'll need something more complex).  (Triggers are treated as simple 'presence on the classpath triggers' in this way if they aren't "springy things" like configuration)

**Comment by aclement** [comment]
I completely forgot that of course you can implement `computeHints` in a hint providing class and then programmatically do what you want. So I refactored LogLevelHints to use that approach.  It seems to work, but I will say I have no samples that need this hint active and because you didn't add an entry to the services file, the hint has never been firing anyway.... (do we really need it?) - I did update the services file for now.
