### ISSUE TITLE
Support for @Valid annotations in Petclinic

### ISSUE THREAD

**Issue by dsyer** [spring-projects-experimental/spring-graalvm-native#309]
Petclinic uses `@Valid` annotations in the web layer, but I don't think they are working. They don't blow up, but they don't actually get validated either. See also #297 and #142.

**Comment by aclement** [comment]
I think this might be because the fields with the constraints on are not being exposed via reflection. So, for example, although the Owner contains:

```
    @Digits(fraction = 0, integer = 10)
    private String telephone;
```

if the system cannot reflect on that at runtime, it won't see the constraint.  In exercising the new owner page on the web app I can make it validate the constraint if I add field reflective access to `Owner` - it then fails by validating but producing the wrong message, I need to add a resource bundle to make that work (and that fixes it).

**Comment by aclement** [comment]
Validation is now working for `petclinic-jdbc` sample. Due to other petclinics using a different component processor (the spring data component processor), I need to do a variant of these changes in that processor too to address all the petclinics.

**Comment by aclement** [comment]
Validation also seems to be working for JPA samples (I had to add the message bundle for validation messages).  I now get a validation error in petclinic-jpa if attempting to add an owner and trying to set the telephone number to an alphabetic string.
