### ISSUE TITLE
 com.sun.proxy.$Proxy548 cannot be cast

### ISSUE THREAD

**Issue by VuDo98** [spring-projects-experimental/spring-graalvm-native#331]
I ran into this error:
`com.sun.proxy.$Proxy548 cannot be cast to org.springframework.cloud.bootstrap.config.PropertySourceLocator`

I already added this class into reflect config but not sure why I got this error. I attached everything in the zip.

[profile.zip](https://github.com/spring-projects-experimental/spring-graalvm-native/files/5426380/profile.zip)

**Comment by aclement** [comment]
Cannot be cast doesn't sound like a configuration issue.  The startup log in the zip file just seems to show the problem from earlier in the week:
```
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.inspira.hub.profile.ProfileServer]; nested exception is org.springframework.core.annotation.AnnotationConfigurationException: A
ttribute 'value' in annotation [org.springframework.web.bind.annotation.RestController] is declared as an @AliasFor nonexistent attribute 'value' in annotation [org.springframework.stereotype.Controller].
```

I don't see an error about casting. I won't be able to make much progress without a sample app that shows something broken to debug. We don't have feign/sleuth/eureka/spring-social-facebook/mapstruct/springfox/firebase samples, so the failures can be due to anything in any of those.

For something we don't have samples for it is worth trying with the agent to collect configuration. I can help you with that if you don't know how to do it.

**Comment by sadew145** [comment]
@aclement I am sorry, the startup log in the zip is wrong.

I did use agent to generate the configs that are included in the zip. The casting error popup both when I am using agent or not.

Here is the log for when I was runnning it with the agent.

[log.txt](https://github.com/spring-projects-experimental/spring-graalvm-native/files/5432218/log.txt)

**Comment by aclement** [comment]
I see the new log, thanks for that. This is really hard to diagnose when I can't recreate though. Given it is occurring in startup, maybe we could have a test app which is just that pom plus an empty SpringApplication, plus the config you are using that is exercising the property source infrastructure (if any).

**Comment by sadew145** [comment]
ok I'll create an empty app to see if I can reproduce it and send it to you. But I am not sure what property source infrastructure is. Can you give any names as an example?

**Comment by sadew145** [comment]
Hi @aclement, here is a demo spring cloud app. All I do is run ` java -jar -Dspring.profiles.active=native target/config-server.jar
` to start config server on JVM. Make sure you fix the config storage path. Although, demoApp won't build due to the same issue as the log I attached above.


[demo.zip](https://github.com/spring-projects-experimental/spring-graalvm-native/files/5441343/demo.zip)

**Comment by aclement** [comment]
Thanks for the app, I'll try it out. In working on something else today I think I know what it might be - I think it'll be that we can't create CGLIB proxies under native-image, only JDK proxies and in some cases those are not sufficient, I think this might be one of those cases.

**Comment by sadew145** [comment]
do you know if there is anything i can do to fix this?

**Comment by aclement** [comment]
Haven't had time to dig into the app yet - it is possible JDK proxies could work if interfaces are added to a class but without knowing the cause I can't say where that pattern needs applying. We will fix the overall issue here in time, I just don't have a quick option at the moment.

**Comment by sadew145** [comment]
ok thanks I will look forward to it.

**Comment by sdeleuze** [comment]
@VuDo98 Please make a try with our latest `0.8.3-SNAPSHOT` and GraalVM 20.3, and if you still see the issue please provide a minimal repro, the current one has too much dependency for making it useful for us to help you.

**Comment by VuDo98** [comment]
Hi @sdeleuze I am still seeing this error with the same previous one with spring graalvm 0.8.3, graalvm 20.3, and spring cloud deps 2020.0.0-SNAPSHOT follow the example in samples. Log (1) is attached. I am not sure if I can reproduce this on a minimal because I tried to run a minimal config on the discovery client sample but it gave me error like log (2).

[log 1.txt](https://github.com/spring-projects-experimental/spring-graalvm-native/files/5611820/log.1.txt)
[log 2.txt](https://github.com/spring-projects-experimental/spring-graalvm-native/files/5611821/log.2.txt)
