### ISSUE TITLE
Support @MVC features being added via library

### ISSUE THREAD

**Issue by dsyer** [spring-projects-experimental/spring-graalvm-native#353]
If a library (e.g. spring-cloud-config-server) adds `@Bean` with `@MVC` annotations (e.g. `@RestController`) I'm not sure we register those classes as resources, and the native image won't be able to look up the annotation metadata. Maybe errors like this:

```
Attribute 'value' in annotation [org.springframework.web.bind.annotation.RestController] is declared as an @AliasFor nonexistent attribute 'value' in annotation [org.springframework.stereotype.Controller].
```

**Comment by aclement** [comment]
The problem here is we have a lovely system for analyzing mvc annotations. However, we don't currently run all that for things coming in from random jars on the classpath (separate to the main project that is being built). It's a known limitation and had to be addressed at some point, i guess this is the bug where we do it.

**Comment by aclement** [comment]
Fixed, I actually think this particular case came down to a missing hint rather than the analysis logic not working.
